import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "dunno what im doing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* You can include other head elements here */}
      </head>
      <body className={inter.className}>
        <nav>
          <ul>
            <li><Link href="/home">Home</Link></li>
            <li><Link href="/about">About</Link></li>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
